### ISSUE TITLE
tsc won't compile with TypeScript 4.1.3

### ISSUE THREAD

**Issue by tschmidt64-SC** [stephenh/ts-proto#195]
I generated typescript using this plugin, but was unable to compile using `tsc` with typescript version 4.1.3. 

Here is a minimal working example:
```protobuf
// events.proto

syntax = "proto3";

message Event {
  uint64 example_num = 10;
}
```

```typescript
// events.ts

/* eslint-disable */
import * as Long from "long";
import { util, configure, Writer, Reader } from "protobufjs/minimal";

export const protobufPackage = "";

export interface Event {
  exampleNum: number;
}

const baseEvent: object = { exampleNum: 0 };

export const Event = {
  // ... generated code here
};

type Builtin = Date | Function | Uint8Array | string | number | undefined;
export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends Array<infer U>
  ? Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U>
  ? ReadonlyArray<DeepPartial<U>>
  : T extends {}
  ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(long: Long): number {
  if (long.gt(Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (util.Long !== Long) {
  util.Long = Long as any;
  configure();
}
```

The if-clause comparing long types at the end fails to compile with error:
```ts
events.ts:82:5 - error TS2367: This condition will always return 'true' since the types 'Constructor<Long>' and '{ default: LongConstructor; prototype: Long; MAX_UNSIGNED_VALUE: Long; MAX_VALUE: Long; MIN_VALUE: Long; NEG_ONE: Long; ONE: Long; ... 11 more ...; fromValue(val: string | ... 2 more ... | { ...; }): Long; }' have no overlap.

82 if (util.Long !== Long) {
       ~~~~~~~~~~~~~~~~~~

Found 1 error.

error Command failed with exit code 2.
```

**Comment by stephenh** [comment]
I'm 90% sure this will be solved by using the `esModuleInterop` flag. Let me know if not, thanks!

**Comment by tschmidt64-SC** [comment]
Interesting. I already had  `esModuleInterop: true` in my `tsconfig.json`, but when I set set it to `false`, it compiled successfully. Is that what you meant? I was under the impression you were suggesting setting it to true.

**Comment by stephenh** [comment]
No, there is a `ts_proto_opt=esModuleInterop=true` flag you have to pass to ts-proto when invoking `protoc` to tell it that you want ts-proto to generate `esModuleInterop`-compliant TypeScript output.

**Comment by livcarman** [comment]
I was having this exact problem and using the `ts_proto_opt=esModuleInterop=true` flag resolved it for me. Thanks!
