### ISSUE TITLE
Code generated by ts-proto 2.4.2 cannot compile with TypeScript >= 5.6 with error `Type 'Buffer' is not assignable to type 'Uint8Array'`

### ISSUE THREAD

**Issue by ddadaal** [stephenh/ts-proto#1143]
Hello, I am trying to use ts-proto with TypeScript >= 5.6, but the code generated by ts-proto (current version 2.4.2) cannot compile with the following error (github action log https://github.com/ddadaal/ts-proto-2.4.2-ts-5.6/actions/runs/12096354580/job/33730555665)

```
generated/test.ts:125:65 - error TS2345: Argument of type 'Buffer' is not assignable to parameter of type 'BinaryReader | Uint8Array'.
  Type 'Buffer' is not assignable to type 'Uint8Array'.
    The types returned by 'entries()' are incompatible between these types.
      Type 'IterableIterator<[number, number]>' is missing the following properties from type 'ArrayIterator<[number, number]>': map, filter, take, drop, and 9 more.

125     responseDeserialize: (value: Buffer) => TestResponse.decode(value),
```

It should be caused by the typing changes introduced in typescript 5.6 [described in this stackoverflow thread](https://stackoverflow.com/questions/78790943/in-typescript-5-6-buffer-is-not-assignable-to-arraybufferview-or-uint8arr). 

But from my testing, ignoring these errors doesn't break anything. Just updating the type annotation from `Buffer` to `Uint8Array` shoud work.

```
    requestDeserialize: (value: Buffer) => TestRequest.decode(new Uint8Array(value)),
```

[This](https://github.com/ddadaal/ts-proto-2.4.2-ts-5.6) is a minimal repro repo.

Can you help fix this issue? Thanks!

## Versions

ts-proto: 2.4.2
typescript: 5.6.2
node: 20

**Comment by stephenh** [comment]
Hi @ddadaal , per the SO thread you linked to, it sounds like upgrading your `@types/node` is the right fix, not a change to ts-proto's output?

I was worried that your suggestion of calling `new Uint8Array(value)` would create a copy of the buffer, but it sounds like it wouldn't, which is good, but I'd still like to have you just bump the `@types/node` dependency in your project, and see if that fixes things?

Thanks!

**Comment by ddadaal** [comment]
OK, updating `@types/node` to `22.10.1` (current latest) fixes the issue. I thought `@types/node` should be kept at `20` since I was running node 20, but it seems the versions between node and `@types/node` doesn't need to match. Thanks for the fix!

Oh I just found out I forgot to remove the code line suggesting `new Uint8Array()`. Even the `@types/node` is at `20`, creating a new Uint8Array is not required. It's just simply typing errors, no runtime code needs to be updated. My suggestion was to just update the type annotation of the `value` parameter to `Uint8Array` like below.

```
   requestDeserialize: (value: Uint8Array) => TestRequest.decode(value),
```

But it may affect existing `requestDeserialize` users, so it seems the only correct solution is to update `@types/node` to `22`.

**Comment by stephenh** [comment]
Good to hear that worked; fwiw the SO lost you linked to insinuated you could stay on a 20.x version of types/node, as long as it was the latest 20.x.

I.e. they back ported the fix into the 20.x release line

**Comment by ddadaal** [comment]
Yes it turned out [20.17.9](https://www.npmjs.com/package/@types/node/v/20.17.9) also fixes the issue.
